<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // \App\Models\User::factory(10)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

        // Create sectors for the sectors table using

        \DB::table('sectors')->insert([
            ['sector_name' => 'A - Agriculture, Forestry and Fishing'],
            ['sector_name' => 'A01 - Crop and animal production, hunting and related service activities'],
            ['sector_name' => 'A02 - Forestry and logging'],
            ['sector_name' => 'A03 - Fishing and aquaculture'],
            ['sector_name' => 'B - Mining and Quarrying'],
            ['sector_name' => 'B05 - Mining of coal and lignite'],
            ['sector_name' => 'B06 - Extraction of crude petroleum and natural gas'],
            ['sector_name' => 'B07 - Mining of metal ores'],
            ['sector_name' => 'B08 - Other mining and quarrying'],
            ['sector_name' => 'B09 - Mining support service activities'],
            ['sector_name' => 'C - Manufacturing'],
            ['sector_name' => 'C10 - Manufacture of food products'],
            ['sector_name' => 'C11 - Manufacture of beverages'],
            ['sector_name' => 'C12 - Manufacture of tobacco products'],
            ['sector_name' => 'C13 - Manufacture of textiles'],
            ['sector_name' => 'C14 - Manufacture of wearing apparel'],
            ['sector_name' => 'C15 - Manufacture of leather and related products'],
            ['sector_name' => 'C16 - Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials'],
            ['sector_name' => 'C17 - Manufacture of paper and paper products'],
            ['sector_name' => 'C18 - Printing and reproduction of recorded media'],
            ['sector_name' => 'C19 - Manufacture of coke and refined petroleum products'],
            ['sector_name' => 'C20 - Manufacture of chemicals and chemical products'],
            ['sector_name' => 'C21 - Manufacture of basic pharmaceutical products and pharmaceutical preparations'],
            ['sector_name' => 'C22 - Manufacture of rubber and plastic products'],
            ['sector_name' => 'C23 - Manufacture of other non-metallic mineral products'],
            ['sector_name' => 'C24 - Manufacture of basic metals'],
            ['sector_name' => 'C25 - Manufacture of fabricated metal products, except machinery and equipment'],
            ['sector_name' => 'C26 - Manufacture of computer, electronic and optical products'],
            ['sector_name' => 'C27 - Manufacture of electrical equipment'],
            ['sector_name' => 'C28 - Manufacture of machinery and equipment n.e.c.'],
            ['sector_name' => 'C29 - Manufacture of motor vehicles, trailers and semi-trailers'],
            ['sector_name' => 'C30 - Manufacture of other transport equipment'],
            ['sector_name' => 'C31 - Manufacture of furniture'],
            ['sector_name' => 'C32 - Other manufacturing'],
            ['sector_name' => 'C33 - Repair and installation of machinery and equipment'],
            ['sector_name' => 'D - Electricity, Gas, Steam and Air Conditioning Supply'],
            ['sector_name' => 'D35 - Electricity, gas, steam and air conditioning supply'],
            ['sector_name' => 'E - Water Supply; Sewerage, Waste Management and Remediation Activities'],
            ['sector_name' => 'E36 - Water collection, treatment and supply'],
            ['sector_name' => 'E37 - Sewerage'],
            ['sector_name' => 'E38 - Waste collection, treatment and disposal activities; materials recovery'],
            ['sector_name' => 'E39 - Remediation activities and other waste management services'],
            ['sector_name' => 'F - Construction'],
            ['sector_name' => 'F41 - Construction of buildings'],
            ['sector_name' => 'F42 - Civil engineering'],
            ['sector_name' => 'F43 - Specialised construction activities'],
            ['sector_name' => 'G - Wholesale and Retail Trade; Repair of Motor Vehicles and Motorcycles'],
            ['sector_name' => 'G45 - Wholesale and retail trade and repair of motor vehicles and motorcycles'],
            ['sector_name' => 'G46 - Wholesale trade, except of motor vehicles and motorcycles'],
            ['sector_name' => 'G47 - Retail trade, except of motor vehicles and motorcycles'],
            ['sector_name' => 'H - Transportation and Storage'],
            ['sector_name' => 'H49 - Land transport and transport via pipelines'],
            ['sector_name' => 'H50 - Water transport'],
            ['sector_name' => 'H51 - Air transport'],
            ['sector_name' => 'H52 - Warehousing and support activities for transportation'],
            ['sector_name' => 'H53 - Postal and courier activities'],
            ['sector_name' => 'I - Accommodation and Food Service Activities'],
            ['sector_name' => 'I55 - Accommodation'],
            ['sector_name' => 'I56 - Food and beverage service activities'],
            ['sector_name' => 'J - Information and Communication'],
            ['sector_name' => 'J58 - Publishing activities'],
            ['sector_name' => 'J59 - Motion picture, video and television programme production, sound recording and music publishing activities'],
            ['sector_name' => 'J60 - Programming and broadcasting activities'],
            ['sector_name' => 'J61 - Telecommunications'],
            ['sector_name' => 'J62 - Computer programming, consultancy and related activities'],
            ['sector_name' => 'J63 - Information service activities'],
            ['sector_name' => 'K - Financial and Insurance Activities'],
            ['sector_name' => 'K64 - Financial service activities, except insurance and pension funding'],
            ['sector_name' => 'K65 - Insurance, reinsurance and pension funding, except compulsory social security'],
            ['sector_name' => 'K66 - Activities auxiliary to financial services and insurance activities'],
            ['sector_name' => 'L - Real Estate Activities'],
            ['sector_name' => 'L68 - Real estate activities'],
            ['sector_name' => 'M - Professional, Scientific and Technical Activities'],
            ['sector_name' => 'M69 - Legal and accounting activities'],
            ['sector_name' => 'M70 - Activities of head offices; management consultancy activities'],
            ['sector_name' => 'M71 - Architectural and engineering activities; technical testing and analysis'],
            ['sector_name' => 'M72 - Scientific research and development'],
            ['sector_name' => 'M73 - Advertising and market research'],
            ['sector_name' => 'M74 - Other professional, scientific and technical activities'],
            ['sector_name' => 'N - Administrative and Support Service Activities'],
            ['sector_name' => 'N77 - Rental and leasing activities'],
            ['sector_name' => 'N78 - Employment activities'],
            ['sector_name' => 'N79 - Travel agency, tour operator, reservation service and related activities'],
            ['sector_name' => 'N80 - Security and investigation activities'],
            ['sector_name' => 'N81 - Services to buildings and landscape activities'],
            ['sector_name' => 'N82 - Office administrative, office support and other business support activities'],
            ['sector_name' => 'O - Public Administration and Defence; Compulsory Social Security'],
            ['sector_name' => 'O84 - Public administration and defence; compulsory social security'],
            ['sector_name' => 'P - Education'],
            ['sector_name' => 'P85 - Education'],
            ['sector_name' => 'Q - Human Health and Social Work Activities'],
            ['sector_name' => 'Q86 - Human health activities'],
            ['sector_name' => 'Q87 - Residential care activities'],
            ['sector_name' => 'Q88 - Social work activities without accommodation'],
            ['sector_name' => 'R - Arts, Entertainment and Recreation'],
            ['sector_name' => 'R90 - Creative, arts and entertainment activities'],
            ['sector_name' => 'R91 - Libraries, archives, museums and other cultural activities'],
            ['sector_name' => 'R92 - Gambling and betting activities'],
            ['sector_name' => 'R93 - Sports activities and amusement and recreation activities'],
            ['sector_name' => 'S - Other Service Activities'],
            ['sector_name' => 'S94 - Activities of membership organisations'],
            ['sector_name' => 'S95 - Repair of computers and personal and household goods'],
            ['sector_name' => 'S96 - Other personal service activities'],
            ['sector_name' => 'T - Activities of households as employers; Undifferentiated goods- and services-producing activities of households for own use'],
            ['sector_name' => 'T97 - Activities of households as employers of domestic personnel'],
            ['sector_name' => 'T98 - Undifferentiated goods- and services-producing activities of private households for own use'],
            ['sector_name' => 'U - Activities of Extraterritorial Organizations and Bodies'],
            ['sector_name' => 'U99 - Activities of extraterritorial organizations and bodies']
        ]);
    }
}
